### ISSUE TITLE
Start code error log.

### ISSUE THREAD

**Issue by tkim-snu** [skaro94/vtt_challenge_2019#3]
I followed all the steps mentioned for training.

I am getting the below error message.

My system configuration:
GPU: Nvidia TITAN Xp
MEM : 64 GB

Can you check this issue?
Thank you.

Loading Image Data
Loading Image Files
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋| 399260/400000 [00:40<00:00, 18634.82it/sException in thread Thread-6:████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                         | 19374/23128 [04:28<00:57, 64.91it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 405, in _handle_workers
    pool._maintain_pool()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 246, in _maintain_pool
    self._repopulate_pool()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by skaro94** [comment]
Hi. First of all, I could not pinpoint the source of the problem since I could not reproduce the error given the information you provided.

With that said, the Error can be caused by various problems; i.e. insufficient memory, insufficient number of file descriptor limit, etc.
Since reducing the number of processes for multiprocessing can be a solution to most of the problems, I suggest you trying that.

You can try this with the following command.

python train.py --num_workers=$NUM

The default $NUM is 40. Please try with a lower number, such as 5 or 10.

**Comment by KyonP** [comment]
> The default $NUM is 40. 

wow. 
이건 필요하면 참가자들에게 공지로 안내를 해야될거같네요.
